name:                hasami
version:             0.1.0.0
github:              "catchouli/hasami"
license:             AllRightsReserved
author:              "Caitlin Wilks"
maintainer:          "mitasuki@gmail.com"
copyright:           "2018 Caitlin Wilks"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/catchouli/hasami#readme>

dependencies:
- base >= 4.7 && < 5
- sdl2
- mtl
- transformers
- lens
- OpenGL
- GLUtil
- bytestring
- vector
- vect
- inline-c

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -fobject-code
- -O2

default-extensions:
- OverloadedStrings
- NoMonomorphismRestriction
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- LambdaCase
- MultiWayIf
- TupleSections
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- StandaloneDeriving
- GeneralizedNewtypeDeriving
- ScopedTypeVariables
- TypeApplications
- DefaultSignatures
- TemplateHaskell
- RankNTypes

library:
  source-dirs: src

data-files:
- res/*.glsl

executables:
  hasami-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hasami

tests:
  hasami-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hasami
